platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronous priority.
# Disable this for faster pod installs.
install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  # FIJAR EL USO DE FRAMEWORKS ESTÁTICOS
  # Esto soluciona los errores de "non-modular header" con Firebase
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # FORZAR PERMISO DE HEADERS NO MODULARES
      # Esta es la cura específica para el error de firebase_messaging
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      
      # Asegurar compatible con iOS 13+
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
