workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          cd flutter_movil
          flutter pub get
      - name: Build APK (Release)
        script: |
          cd flutter_movil
          flutter build apk --release --no-pub
    artifacts:
      - flutter_movil/build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - gustavo.lira@tucorreo.com # Reemplazar si tienes uno específico configurado
        notify:
          success: true
          failure: true
